<a href="https://colab.research.google.com/github/primalkriek/stuff/blob/main/Copy_of_00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.8298, 0.7110, 0.1111, 0.2097, 0.0999, 0.2927, 0.6939],
        [0.6665, 0.3775, 0.8479, 0.1724, 0.1580, 0.8017, 0.3126],
        [0.9553, 0.9857, 0.8258, 0.7832, 0.8561, 0.9530, 0.8786],
        [0.6933, 0.5546, 0.8837, 0.7865, 0.7303, 0.2159, 0.3849],
        [0.5094, 0.9543, 0.4441, 0.2654, 0.8614, 0.6372, 0.8006],
        [0.7425, 0.1417, 0.9910, 0.3489, 0.8822, 0.7213, 0.6045],
        [0.4117, 0.7326, 0.8383, 0.1018, 0.8363, 0.0463, 0.5124]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor1 = torch.rand(2)
print(tensor1)
tensor2 = torch.rand(1,7)
# Perform matrix multiplication
print (tensor2, tensor2.shape)
new_tensor2 = tensor2.T
multiplied_tensor= new_tensor2 *tensor1

print(multiplied_tensor)


tensor([0.3677, 0.8649])
tensor([[0.4623, 0.6869, 0.5646, 0.6749, 0.5659, 0.3651, 0.7759]]) torch.Size([1, 7])
tensor([[0.1700, 0.3999],
        [0.2525, 0.5941],
        [0.2076, 0.4884],
        [0.2481, 0.5838],
        [0.2080, 0.4894],
        [0.1342, 0.3158],
        [0.2853, 0.6711]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors

tensor3 = torch.rand(size=(7, 7))
tensor4 = torch.rand(size=(1,7))

print(tensor3)
print(tensor4)


# Matrix multiply tensors
multiplied_tensor3_and_tensor4 = torch.matmul(tensor3,tensor4.T)
print(multiplied_tensor3_and_tensor4, multiplied_tensor3_and_tensor4.shape)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor5 = torch.rand(size=(2,3))
tensor5.to(device)
tensor6 = torch.rand(size=(2,3))
tensor6.to(device)
print(device)
print(tensor5)
print(tensor6)

cuda
tensor([[0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143]])
tensor([[0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
