<a href="https://colab.research.google.com/github/primalkriek/stuff/blob/main/tensor_curving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### indexing (selecting data from tensors)

indexing with pytorch is similar to indexing with numpy

In [2]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
# let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [10]:
# let's index on inner bracket
x[0][2][2]

tensor(9)

In [12]:
# a : can also be used to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [15]:
# get all values of the 0th dimension and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [17]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
# watch specifically that there are square brackets around the 5, in codeblock 10 it is only brackets returned
x[:,1,1]

tensor([5])

In [32]:
#index on x to return 9
print(x[:,2,2])
print(x[0][2][2])


tensor([9])
tensor(9)


In [30]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

### pytorch and numpy
numpy is a popular scientific python numerical computing torch.library, and because of this Pytorch has functionality to interact with it
* data in numpy, want in pytorch tensor -> torch.torch.from_numpy(ndarray)
* pytorch tensor -> numpy -> torch.tensor.numpy()


In [35]:
# numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning when converting from numpy to pytorch, pytorch reflects default numpy datatype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [37]:
#change the value of array
array = array +1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [39]:
# from pytorch to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # again warning the tensor default type gets reflected in numpy array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [41]:
#what happens when we change the tensor
tensor = tensor +1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducibility (trying to take the random out of random)
a neural network learns like this:
start with random number -> tensor operations -> update random numbers to try and make them representations of the data -> again -> again -> again

to reduce the randomness in neural networks and pytorch comes the concept of random seed

essentaially what the random seed does is flavour the randomness

In [47]:
import torch
#create random tensors
tensora = torch.rand(3,4)
tensorb = torch.rand(3,4)

print(tensora)
print(tensorb)
print(tensora == tensorb)

tensor([[0.0011, 0.2983, 0.6977, 0.8724],
        [0.2131, 0.4755, 0.2316, 0.1943],
        [0.0301, 0.7232, 0.0186, 0.4213]])
tensor([[0.1823, 0.4229, 0.6875, 0.7398],
        [0.2844, 0.8990, 0.5944, 0.5281],
        [0.2989, 0.4665, 0.9185, 0.4963]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [50]:
#random but reproducible tensors
import torch

#random seed
RANDOM_SEED = 49
torch.manual_seed(RANDOM_SEED)
tensorc = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) #needs to be done when calling the torch.rand again
tensord = torch.rand(3,4)

print(tensorc)
print(tensord)
print(tensorc == tensord)

tensor([[0.0469, 0.2767, 0.2478, 0.9267],
        [0.1418, 0.7192, 0.2505, 0.2332],
        [0.9189, 0.6753, 0.1225, 0.2415]])
tensor([[0.0469, 0.2767, 0.2478, 0.9267],
        [0.1418, 0.7192, 0.2505, 0.2332],
        [0.9189, 0.6753, 0.1225, 0.2415]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


https://pytorch.org/docs/stable/notes/randomness.html

https://www.w3schools.com/python/ref_random_seed.asp


## running tensors and pytorch object run on GPU and make them faster

GPU = cuda + nvidia hardware + pytorch working behind the scenes

### getting a gpu
1. easiest - use colab for a free gpu (or upgrade)
2. use your own gpu
3. use cloud computing GCP, AWS,

In [1]:
!nvidia-smi

Wed Sep 20 20:09:22 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
torch.cuda.is_available()

True

In [5]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

for pytorch since it is capable of computing on the gpu it is best to check what is available, device agnostic code
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [7]:
torch.cuda.device_count()

1

### putting tensors and models on the GPU

for faster computation of course


In [9]:
# create a tensor default on cpu
tensor = torch.tensor([1,2,3])

# not on gpu, check
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [11]:
#putting tensor on gpu
tensor_ongpu = tensor.to(device)
tensor_ongpu


tensor([1, 2, 3], device='cuda:0')

### move tensors back to cpu because numpy runs only on cpu


In [15]:
#tensor is on gpu
#put it back on CPU
tensor_backtocpu = tensor_ongpu.cpu()
tensor_backtocpu.numpy()

array([1, 2, 3])