<a href="https://colab.research.google.com/github/primalkriek/stuff/blob/main/tensor_curve.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

startup

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.0.1+cu118


introduction tensors
creating a tensor with torch.tensor() reference: https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get the tensor back as python int
scalar.item()


7

In [ ]:
#vector
vector = torch.tensor([7,4])
vector

tensor([7, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.size()

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                      [6,9]])
MATRIX

tensor([[7, 8],
        [6, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.size()

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([6, 9])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.size()

torch.Size([1, 3, 3])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### random tenor

random tensors are important because the way neural networks learn.  they start with a tensors full of random numbers and adjust those random numbers to better represent the data
documentation: https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
#generate random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0405, 0.6485, 0.4747, 0.7843],
        [0.1237, 0.2934, 0.1304, 0.9401],
        [0.1525, 0.3125, 0.8480, 0.1878]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))#height, with, colour channels
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### creating a range of tensors and tensors-like

*   range is deprecated, use arange


In [ ]:
### creating a range of tensors
one_to_ten = torch.arange(1,11)
one_to_ten



tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
jump_to_thousand = torch.arange(start= 1, end=1000, step=10)
jump_to_thousand

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271,
        281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411,
        421, 431, 441, 451, 461, 471, 481, 491, 501, 511, 521, 531, 541, 551,
        561, 571, 581, 591, 601, 611, 621, 631, 641, 651, 661, 671, 681, 691,
        701, 711, 721, 731, 741, 751, 761, 771, 781, 791, 801, 811, 821, 831,
        841, 851, 861, 871, 881, 891, 901, 911, 921, 931, 941, 951, 961, 971,
        981, 991])

In [ ]:
#tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes
location of datatype descriptions: https://pytorch.org/docs/stable/tensors.html#data-types

16 bit vergt minder rekenkracht omdat het minder bits is

**note**: tensor datatypes is one of the 3 big errors you can run into with pytorch and deeplearning:
1. tensors not the right data type
2. tensors not in the right shape
3. tensors not on the right device

precision in computing:

https://en.wikipedia.org/wiki/Precision_(computer_science)

https://en.wikipedia.org/wiki/Single-precision_floating-point_format



In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.00,9.0],
                              dtype=None, #what is the datatype (float16 or float32)
                               device=None, #what devie is the tensor on? cuda, cpu
                               requires_grad=False) # wether or not to track the gradientst of the tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
bit_64_tensor = torch.tensor([3,6,9], dtype=torch.long)


In [ ]:
float_32_tensor * bit_64_tensor

tensor([ 9., 36., 81.])

### getting information from tensors
tensors not the right data type - to get the datatype use tensor.dtype
tensors not in the right shape - to get the right shape use tensor.shape
tensors not on the right device - to get the right device use tensor.device

In [ ]:
#create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0057, 0.6645, 0.8162, 0.6114],
        [0.3622, 0.1084, 0.9932, 0.5766],
        [0.8192, 0.2788, 0.6777, 0.7796]])

In [ ]:
#find out the details
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype} ")
print(f"shape of the tensor: {some_tensor.shape}")
print(f"device of the tensor: {some_tensor.device}")

tensor([[0.0057, 0.6645, 0.8162, 0.6114],
        [0.3622, 0.1084, 0.9932, 0.5766],
        [0.8192, 0.2788, 0.6777, 0.7796]])
datatype of tensor: torch.float32 
shape of the tensor: torch.Size([3, 4])
device of the tensor: cpu


### manipulating tensors (tensor operations)

tensor operations include:
+ additioin
- subtraction
* multiplication
- division
- matrix dvision (https://www.mathsisfun.com/algebra/matrix-multiplying.html)

In [ ]:
# create a tensor and add 10
tensor_add = torch.tensor([1,2,3])
tensor_add + 10 #or torch.add

tensor([11, 12, 13])

there are 2 types of matrix multiplication
1. element-wise
2. matrix multiplication (dot product)

more information on matrix multiplication see url in previous text field

there are 2 main rules that needs to be satisfied when  multiplying matrix:
1. the **inner dimensions** must match:
(3,2) @ (2,3) won't work
(2,3) @ (3,2) will work
(3,2) @ (2,3) will work
2. the resulting matrix has the shape of the outer dimensions

In [ ]:
# create a tensor and multiply by 10

tensor_add * 10

tensor([10, 20, 30])

In [ ]:
tensor_add

tensor([1, 2, 3])

In [ ]:
# create a tensor and substract 10

tensor_add - 10

tensor([-9, -8, -7])

In [ ]:
#element wise multiplication
print(tensor_add,"*",tensor_add)
print(f"equals: {tensor_add*tensor_add}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor_add,tensor_add)

tensor(14)

In [ ]:
%%time
value = 0
for i in range (len(tensor_add)):
  value +=tensor_add[i] * tensor_add[i]
print(value)

tensor(14)
CPU times: user 2.58 ms, sys: 18 µs, total: 2.6 ms
Wall time: 7.51 ms


In [ ]:
%%time
torch.matmul(tensor_add,tensor_add)

CPU times: user 126 µs, sys: 0 ns, total: 126 µs
Wall time: 132 µs


tensor(14)

### one of the most common errors in tensors is shape


inner dimensions must match

http://matrixmultiplication.xyz/

In [ ]:
tensor_add @ tensor_add

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # will work, inner dimensions the same.
# won't work torch.matmul(torch.rand(2,3),(torch.rand(2,3)))

tensor([[0.5639, 1.0200, 0.1877],
        [0.0909, 0.3657, 0.1133],
        [0.3446, 0.5334, 0.0776]])

In [ ]:
# shapes for matrix multi

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])



In [ ]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


to fix our tensor shape issues we can manipulate the shape of one of our tensors using **transpose**

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# this will give an error because inner dimensions don't match -> torch.mm(tensor_A,tensor_B) #torch.mm is matmul alias
# torch.mm(tensor_A,tensor_B.T) #this does work, because we transpose tensor_B

print (f"original shape of tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"transposed tensor_B: {tensor_B.T}")
print(f"multiplying these: {tensor_A.shape} @ {tensor_B.T.shape} <- innner dimensions match")
print("output: ")
output=torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"output shape: {output.shape}")

original shape of tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
transposed tensor_B: tensor([[ 7,  8,  9],
        [10, 11, 12]])
multiplying these: torch.Size([3, 2]) @ torch.Size([2, 3]) <- innner dimensions match
output: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
output shape: torch.Size([3, 3])


### finding the MIN, MAX, MEAN, SUM, ETC (tensor aggregation)

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x
x.dtype

torch.int64

In [ ]:
#find the MIN
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the MAX
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean, but datatype needs to be float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean ()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding odd max and odd min

In [ ]:
#finding the positional min and max
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


## reshaping, stacking, squeezing and unsqueezing tensors
* reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor fo certain shape but keep the same memory as the original torch.tensor
*sttacking - coming multiple tensors on top of each other (vsttack) or side by side (hstack)
* squeeze - removes all 1 dimensions from a tensor
* unsqueeze -^add a 1 dimension to a target tensorm
*permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
#create a tensor
new_x = torch.arange(1.,10.)
new_x, new_x.shape, new_x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
#add an extra dimension
new_x_reshaped = new_x.reshape(9,1)
new_x_reshaped, new_x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
other_new_x = torch.arange(1,11)
other_new_x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
reshape_other_new_x = other_new_x.reshape(2,5)
reshape_other_new_x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [ ]:
#change the view